version: '3.8'

services:
  app:
    container_name: eduzz-market
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: eduzz
      POSTGRES_PASSWORD: eduzz
      POSTGRES_DB: eduzz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local